spring:
  jpa:
    database: DERBY
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    platform: derby
    url: jdbc:derby:jacks;create=true
    username: sa
    password:
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver